### ISSUE TITLE
Questions about the implementation

### ISSUE THREAD

**Issue by LamaAni** [simagix/hummingbird#1]
Hi

Thank you for writing this repo. Just some small questions.

1. When you do the initial sync, do you allow for bookmark (ish) files?
2. How do you keep the synchronization between the databases (in case the sync restarts)?
3. Is there any mechanism that allows for recovery after the sync restarts (machine restarts, etc)?
4. Would you recommend this for a continues sync between databases?

**Comment by simagix** [comment]
Not sure what you mean about bookmark files for init sync.  For other questions, hummingbird supports them.  Read my mongopush blogs at https://www.simagix.com/.  In short, migration or syncing states are kept in database and hummingbird is smart enough to figure it out.
