### ISSUE TITLE
Unable to apply update ops from tailed oplogs 

### ISSUE THREAD

**Issue by divu911** [simagix/hummingbird#2]
I am facing an issue where migration is able to clone the collections just fine but when it starts to apply tailed oplogs, it ends up with the below error.
"BulkWrites exception: replacement document cannot contain keys beginning with '$"

Apparently, I found that it started happening in MongoDB version >=4.2 

https://github.com/simagix/hummingbird/blob/master/oplog_utils.go#L250

I initially tried mongopush, got same error. Then I used hummingbird, still the same error. Any help is really appreciated

**Comment by simagix** [comment]
I can take a look if can include the oplog cacusing this.

**Comment by divu911** [comment]
Thanks a lot. Really appreciate your help @simagix

**Comment by divu911** [comment]
Hi @simagix Unfortunately I lost the oplogs that were created inside snapshot directory but I queried the oplog operations where the sync is failing. Note that it only fails for operations having below format of "o" field 

`{
    op: 'u',
    ns: 'percona.colltest',
    ui: new UUID("d46f1fb2-4160-4369-8f0e-282ca5d87bcf"),
    o: { '$v': 2, diff: { u: { fld0: Long("943024") } } },
    o2: { _id: { w: 3, i: 102748 } },
    ts: Timestamp({ t: 1670336943, i: 10 }),
    t: Long("1"),
    v: Long("2"),
    wall: ISODate("2022-12-06T14:29:03.024Z")
  }`

And here are the errors captured. Took few of them actually as there were lots

> 2022-12-06T14:28:57Z E replacement document cannot contains keys beginning with '$ &{<nil> <nil> [{_id [{w 0} {i 20347}]}] [{$v 2} {diff [{u [{fld0 750105}]}]}] <nil>}
2022-12-06T14:28:57Z E replacement document cannot contains keys beginning with '$ &{<nil> <nil> [{_id [{w 2} {i 29561}]}] [{$v 2} {diff [{u [{fld0 750105}]}]}] <nil>}
2022-12-06T14:28:57Z E replacement document cannot contains keys beginning with '$ &{<nil> <nil> [{_id [{w 1} {i 40927}]}] [{$v 2} {diff [{u [{fld0 750105}]}]}] <nil>}
2022-12-06T14:28:57Z E replacement document cannot contains keys beginning with '$ &{<nil> <nil> [{_id [{w 3} {i 35591}]}] [{$v 2} {diff [{u [{fld0 750105}]}]}] <nil>}

Below steps I took to reproduce.
1. Install Mongo v5.0 or greater
2. Run updateOne or replaceOne operation. Just an example 
`db.demo.insert({'x':1})`
`db.divyanshu.updateOne({'x':1},{$set:{'x':10}})`
`db.divyanshu.updateOne({'x':10},{$set:{'y':{'z':true}}})`
3. Capture the mongopush or hummingbird status

**Comment by simagix** [comment]
I haven't seen this format before and thus it was not supported.  Because the lack of document, we'll have to reverse engineering it.  I don't actively maintain it and you should use officially supported tools fro MongoDB if this is an urgent matter.

**Comment by simagix** [comment]
If you're willing to test this, pull the https://github.com/simagix/hummingbird/tree/issue2 branch.  Please test and report back before I merge to master.
