### ISSUE TITLE
NewMigratorInstance failed: ParseURI failed: <nil> exit status 1

### ISSUE THREAD

**Issue by gilliganc** [simagix/hummingbird#4]
Trying to connect to 2 stand alone mongo instances running offical mongo docker image and always get the error
```
NewMigratorInstance failed: ParseURI failed: <nil>
exit status 1
```

Tried with and without directConnection=true with no sucuss. I am not sure if this is a bug or something to do with the connection string but looking at the code it looks like the cluster connection stringis coming back empty which makes sense as it is not a cluster but the code is not quite handing it right. If it is due to the connection string not being right is it possible to add a valid cluster and standalone connection string the tothe doco as an example?

i think this is coming from master branch migrator.go line 96
```
for _, replica := range list {
		cs, err := mdb.ParseURI(replica)
		if err != nil || cs.ReplicaSet == "" {
			return nil, fmt.Errorf("ParseURI failed: %v", err)
		}
		inst.Replicas()[cs.ReplicaSet] = replica
	}
```

I fixed this locally with the following change to the above code

```
for _, replica := range list {
		cs, err := mdb.ParseURI(replica)
		if err != nil {
			return nil, fmt.Errorf("ParseURI failed: %v", err)
		} 
		if cs.ReplicaSet == "" {
			fmt.Printf("No Replica Set so standalone!\r\n")
			inst.Replicas()[cs.ReplicaSet] = replica
		} else {
			inst.Replicas()[cs.ReplicaSet] = replica
		}
	}
```

**Comment by simagix** [comment]
Fixed
