### ISSUE TITLE
Update not replicating when source is mongoDB 6.0 and destination is mongoDB 5.0

### ISSUE THREAD

**Issue by farisam** [simagix/hummingbird#5]
Hi @simagix , 

Thank you for the powerful tool like hummingbird. 

Today I just want to report if the update statement is not replicating to mongoDB 5.0 (when the source is mongoDB 6.0). Do you also experiencing this? If yes any workaround for this problem?

**Comment by simagix** [comment]
I suspect that it's a similar problem [as issue 2](https://github.com/simagix/hummingbird/issues/2).  I haven't tested with later version of MongoDB.  Please provide error messages and steps to reproduce.

**Comment by farisam** [comment]
yeah should be same for the error.

so error message is only this `2023-02-14T19:32:22+07:00 W BulkWrites exception: replacement document cannot contains keys beginning with '$`

and Below steps to reproduce :

1. Setup Mongo v5.0 on Atlas MongoDB as source, and setup Atlas Mongo v4.2 on Atlas MongoDB as target.
2. Create database `sample` on source
3. Run `go run main/hummingbird.go -start configuration.json`
4. Run `db.sample.insert({'column':"test_insert"})`
5. Run `db.sample.updateOne({'column':"test_insert"},{$set:{'column':"test_update"}})`
6. Capture the mongopush or hummingbird status
7. Select the data on target, only insert statement will applied to target

Thank you @simagix

**Comment by simagix** [comment]
If you're willing to test this, pull the https://github.com/simagix/hummingbird/tree/issue2 branch.  Please test and report back before I merge to master.

**Comment by farisam** [comment]
let me try it now @simagix , thank you so much

**Comment by farisam** [comment]
hi @simagix , thank you so much, everything goes well now.

I reproduce with 2 test case :

1. source mongodb atlas v5.0 and target using mongodb atlas v4.2
- doing update and insert -> data reflected to target and no error `W BulkWrites exception: replacement document cannot contains keys beginning with '$` occurs

2. source mongodb atlas v6.0 and target using mongodb atlas v4.2
- doing update and insert -> data reflected to target and no error `W BulkWrites exception: replacement document cannot contains keys beginning with '$` occurs`

Thank you for the changes, this really helpful. You can merge to master.

**Comment by farisam** [comment]
hi @simagix , I just realized, I can apply `MongoPush` as `Bi-Directional Replication` by fixing the backwards compatibility. And also I've been tested this and all works.
