### ISSUE TITLE
Supported mongo versions

### ISSUE THREAD

**Issue by akhil-chhugani** [simagix/hummingbird#9]
Is this tool only supported on certain mongo versions we are syncing from a sharded cluster on `v5.0.17` and it is failing to split chunks because the `ns` column does not appear on our `config.chunks` collection. Is this is something that has come up before and is there a workaround?

**Comment by simagix** [comment]
Later versions use uuid instead of ns in `config.chunks`.  Until the codes are modified, you can pre-split the chunks and comment out the error out codes.  MongoDB has a solution called mongosync.
